- name: installing collectd
  apt: name=collectd state=present

- name: deploying configuration
  copy: src=collectd.conf dest=/etc/collectd/collectd.conf
  notify: restart collectd

- meta: flush_handlers

