
- name: installing dependencys
  apt: name={{item}} state=present
  with_items:
       - jq
       - iptables

- name: deleting old cronjob
  cron: name="Update firewall"
        minute="*"
        job="/var/lib/Supernodes/iptables.sh"
        state=absent

- name: deleting old cronjob two
  cron: name="Update firewall (Supernode)"
        minute="*"
        job="/var/lib/Supernodes/iptables-supernode.sh"
        state=absent

- name: creating new cronjob
  cron: name="Update firewall (Supernode)"
        minute="*"
        job="/var/lib/Supernodes/configs/0-common/iptables-supernode.sh"
        state=present

        
- name: reload iptables
  command: /var/lib/Supernodes/configs/0-common/iptables-supernode.sh
  changed_when: False
