---
- name: reload apparmor
  service: name=apparmor state=reloaded

- name: restart dhcpd
  service: name=isc-dhcp-server state=restarted

- name: start dhcpd
  service: name=isc-dhcp-server state=started

- name: reload rsyslog
  service: name=rsyslog state=restarted
