- name: packages are up to date
  apt: update_cache=yes cache_valid_time=3600 upgrade=dist

- name: Autoremove unused packages
  command: apt-get -y autoremove
  register: autoremove_output
  changed_when: "'The following packages will be REMOVED' in autoremove_output.stdout"
