---

- name: restart networking
  shell: ifdown {{ item }} && ifup {{ item }}
  with_items:
    - lo
    - br-fftr
    - fftr-mesh-vpn
    - bat0
    - eth0

- name: load rc.local
  command: /etc/rc.local
  changed_when: False
