#- name: installing dependencys
#  apt: name={{ item }} state=present
#  with_items:
#      - python3-netifaces
#      - python3-pip
#      - python3-setuptools

#- name: installing more dependencys
#  pip: name=py-cpuinfo executable=pip3

  # we use YANIC and respondd.py now
#- name: checkout ffnord-alfred-announce
#  git: repo=https://github.com/freifunk-mwu/ffnord-alfred-announce.git
#       dest=/usr/local/src/ffnord-alfred-announce
#       version=9399a37f5659fb49953e0a155d9cce7f8209b891