- name: install python and python-apt
  raw: sudo apt-get install -y python python-apt

- name: install basic tools
  apt: name={{item}} state=present
  with_items:
    - vim
    - htop
    - iftop
    - mtr
    - dnsutils
    - man
    - arping
    - screen
    - make
