
- name: deploying update-icvpnmeta.sh
  copy: src=update-icvpnmeta.sh dest=/usr/local/bin/update-icvpnmeta.sh mode=755

- name: deploy cron
  cron: name="Update icvpn-meta" minute="43" hour="11" job="/usr/local/bin/update-icvpnmeta.sh > /dev/null 2>&1"